### ISSUE TITLE
400 Bad Request: If Field Characters Are Over Limits

### ISSUE THREAD

**Issue by conrmahr** [3ventic/discord-rss#4]
Articles with a lot of content, triggers Discord Webhook `400 Bad Request` errors in the console log. This is probably due to the char limits Discord sets for each field. See below:

> username: 1-80 characters
content: 2000 characters
embeds: 10 embed objects
title: 256 characters
description: 2048 characters
author[name]: 256 characters
fields: 25 field objects
field[name]: 256 characters
field[value]: 1024 characters
footer[text]: 2048 characters
sum of all characters in embed: 6000 characters
https://discord.com/developers/docs/resources/webhook#execute-webhook

**Comment by 3ventic** [comment]
Fixed in 38e43422b0a502e8b64ee67991c59f37e4089d14
